# Generated by Django 4.2.2 on 2023-06-24 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='b_estado',
            new_name='b_state',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='pk_i',
            new_name='pk_id',
        ),
    ]
