version: '3.7'
services:
  bd_front:
    image: patrones-front:1.0
    networks:
      - proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints: [node.hostname==juferoga]    
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.front-patrones.rule=host(`patrones.juferoga.live`)"
        - "traefik.http.routers.front-patrones.entrypoints=websecure"
        - "traefik.http.routers.front-patrones.service=front-patrones"
        - "traefik.http.services.front-patrones.loadbalancer.port=80"
        - "traefik.port=80"
networks:
    proxy:
      external: true
