# Generated by Django 4.2.2 on 2023-06-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=255, verbose_name='Nombre cinema')),
                ('t_description', models.TextField(max_length=255, verbose_name='Descripción')),
            ],
        ),
    ]
