# Generated by Django 4.2.2 on 2023-06-23 19:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=255, null=True, verbose_name='Nombre del producto')),
                ('t_descripcion', models.CharField(max_length=255, null=True, verbose_name='Descripción del producto')),
                ('n_valoracion', models.IntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('t_tipo', models.CharField(choices=[(1, 'Snack'), (2, 'Ticket')], max_length=255, verbose_name='Tipo de producto')),
                ('n_precio', models.IntegerField(blank=True, null=True)),
                ('fk_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductoGeneral', to='user.client')),
            ],
        ),
    ]
