# Generated by Django 4.2.2 on 2023-06-24 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theater',
            old_name='pk_i',
            new_name='pk_id',
        ),
        migrations.AlterField(
            model_name='theater',
            name='fk_cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Theaters', to='cinema.cinema'),
        ),
    ]
